# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths: [ "src/main/resources/**/*" ]
  pull_request:
    branches: [ "main" ]
    paths: [ "src/main/resources/**/*" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: mshick/add-pr-comment@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: |
            ** WARNING - You are committing changes to properties files under the resources folder. Please validate if the necessary properties are committed to both India and UAE Properties files. Failure to validate can cause servers to fail during startup and thereby cause potential business loss. **
          reactions: eyes  
          allow-repeats: true
