# This Github Actions Workflow is intended to add a Warning comment on any PR which commits changes
# to any property files in India and UAE folders in OrderManagementService repository.

# We want to warn the developers committing changes to properties files in OrderManagementService when
# 1. They raise a PR against main branch
# 2. When the PR gets merged to the main branch

# Author: manichandrakant.velamuri@theporter.in

# @@@@@ Note for future considerations @@@@@
# Any international launches in the future can add more folders containing properties files.
# The current path filter will only cater to properties files that are under the "" folder.
# Any source folders containing property files getting added in other places in the OrderManagementRepository,   should be added to the path filter. 
# The paths element under push or pull_request is an array and can accept multiple entries separated by commas.

name: warn-developers-when-committing-to-properties-files-in-oms

# on is a trigger and Controls when the workflow will run
# This workflow is triggered on push or pull request events but only for the "main" branch
on:
  push:
    branches: [ "master", "main" ]
    paths: [ "src/main/resources/**/*" ]
  pull_request:
    branches: [ "master", "main" ]
    paths: [ "src/main/resources/**/*" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
# our job name is warn-devs
  warn-devs:
    runs-on: ubuntu-latest
    steps:
      - uses: mshick/add-pr-comment@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: |
            :eyes: WARNING - You are committing changes to properties files under the resources folder. Please validate if the necessary properties are committed to both India and UAE Properties files. Failure to validate can cause servers to fail during startup and thereby cause potential business loss. :eyes:
          allow-repeats: true
